name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: I'm trying to detect...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - New Detector
        - CLI Enhancement
        - Output Format
        - Performance
        - Integration (CI/IDE)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, show example code this feature would detect
      render: kotlin

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
