//! Integration tests for committed generated code: a file with a
//! "Generated by / DO NOT EDIT / @generated" header lies about who
//! uses what — its references prove no human intent, and its
//! declarations are not hand-maintained code to clean up. Such files
//! are excluded from the graph entirely.

use std::fs;
use std::path::Path;
use std::process::Output;

fn run(dir: &Path) -> Output {
    std::process::Command::new(env!("CARGO_BIN_EXE_searchdeadcode"))
        .arg(dir)
        .output()
        .unwrap()
}

fn stdout_of(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).to_string()
}

#[test]
fn a_generated_file_is_not_a_source_of_life() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(
        temp.path().join("LegacyModel.kt"),
        "package sample\n\nclass LegacyModel {\n    fun weigh() = 0\n}\n",
    )
    .unwrap();
    // only the committed generated file references LegacyModel
    fs::write(
        temp.path().join("ProtoAdapter.kt"),
        concat!(
            "// Generated by protoc. DO NOT EDIT!\n",
            "package sample\n\n",
            "class ProtoAdapter {\n",
            "    fun adapt() = LegacyModel().weigh()\n",
            "}\n",
        ),
    )
    .unwrap();
    fs::write(
        temp.path().join("Main.kt"),
        "package sample\n\nfun main() {\n    println(\"alive\")\n}\n",
    )
    .unwrap();

    let stdout = stdout_of(&run(temp.path()));
    assert!(
        stdout.contains("'LegacyModel'"),
        "a reference from generated code proves nothing, stdout was:\n{stdout}"
    );
}

#[test]
fn declarations_in_generated_files_are_not_reported() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(
        temp.path().join("ProtoBlob.kt"),
        concat!(
            "// Generated by the protocol buffer compiler.\n",
            "package sample\n\n",
            "class ProtoBlob {\n",
            "    fun marshal() {}\n",
            "}\n",
        ),
    )
    .unwrap();
    fs::write(
        temp.path().join("Main.kt"),
        "package sample\n\nfun main() {\n    println(\"alive\")\n}\n",
    )
    .unwrap();

    let stdout = stdout_of(&run(temp.path()));
    assert!(
        !stdout.contains("'ProtoBlob'"),
        "generated declarations are not ours to clean up, stdout was:\n{stdout}"
    );
}

#[test]
fn an_at_generated_marker_counts_too() {
    let temp = tempfile::tempdir().unwrap();
    fs::write(
        temp.path().join("SchemaBlob.kt"),
        concat!(
            "/* @generated by openapi-codegen */\n",
            "package sample\n\n",
            "class SchemaBlob {\n",
            "    fun read() {}\n",
            "}\n",
        ),
    )
    .unwrap();
    fs::write(
        temp.path().join("Main.kt"),
        "package sample\n\nfun main() {\n    println(\"alive\")\n}\n",
    )
    .unwrap();

    let stdout = stdout_of(&run(temp.path()));
    assert!(
        !stdout.contains("'SchemaBlob'"),
        "@generated is a standard marker, stdout was:\n{stdout}"
    );
}

#[test]
fn a_late_mention_of_generation_does_not_exclude_the_file() {
    let temp = tempfile::tempdir().unwrap();
    // "generated" appears deep in the file, not as a header
    let mut body = String::from("package sample\n\n");
    for i in 0..10 {
        body.push_str(&format!("fun filler{i}() = {i}\n"));
    }
    body.push_str("// this report was generated by hand, ironically\n");
    body.push_str("class RealCode {\n    fun act() {}\n}\n");
    fs::write(temp.path().join("RealCode.kt"), body).unwrap();
    fs::write(
        temp.path().join("Main.kt"),
        "package sample\n\nfun main() {\n    println(\"alive\")\n}\n",
    )
    .unwrap();

    let stdout = stdout_of(&run(temp.path()));
    assert!(
        stdout.contains("'RealCode'"),
        "a stray comment mid-file is not a header — the file stays in the graph, stdout was:\n{stdout}"
    );
}
