//! --init: generate a commented .deadcode.yml matching the project's shape.

use crate::discovery::detect_phantom_source_sets;
use std::fs;
use std::path::Path;

/// Scan the project and write a starter config. Returns an error message
/// instead of clobbering an existing one.
pub fn generate_config(project_root: &Path) -> Result<String, String> {
    let config_path = project_root.join(".deadcode.yml");
    if config_path.exists() {
        return Err(format!(
            "{} already exists — delete it first if you want a fresh one",
            config_path.display()
        ));
    }

    let phantom_dirs = detect_phantom_source_sets(project_root).phantom_dirs;
    let di_framework = detect_di_framework(project_root);

    let mut out = String::new();
    out.push_str("# Generated by searchdeadcode --init\n");
    out.push_str("# Adjust and commit: this file is the project's ground truth.\n\n");

    out.push_str("targets:\n  - \".\"\n\n");

    out.push_str("exclude:\n");
    out.push_str("  - \"**/build/**\"\n");
    out.push_str("  - \"**/generated/**\"\n");
    out.push_str("  - \"**/.gradle/**\"\n");
    for dir in &phantom_dirs {
        let rel = dir.strip_prefix(project_root).unwrap_or(dir);
        out.push_str(&format!(
            "  # Not part of any build (phantom source set)\n  - \"**/{}/**\"\n",
            rel.file_name().unwrap_or_default().to_string_lossy()
        ));
    }
    out.push('\n');

    match di_framework {
        Some(name) => out.push_str(&format!(
            "# DI framework detected: {}. Providers are roots only when their\n# produced type is consumed; add entry_points here if bindings are\n# consumed from outside the analyzed sources.\n",
            name
        )),
        None => out.push_str("# No DI framework detected.\n"),
    }
    out.push_str("entry_points: []\n\n");

    out.push_str("retain_patterns: []\n\n");

    out.push_str("android:\n");
    out.push_str("  parse_manifest: true\n");
    out.push_str("  parse_layouts: true\n");
    out.push_str("  auto_retain_components: true\n");

    fs::write(&config_path, &out).map_err(|e| e.to_string())?;
    Ok(config_path.display().to_string())
}

/// Best-effort DI framework detection from source contents
fn detect_di_framework(project_root: &Path) -> Option<&'static str> {
    let mut stack = vec![project_root.to_path_buf()];
    let mut checked = 0usize;
    while let Some(dir) = stack.pop() {
        let Ok(entries) = fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if path.is_dir() {
                if !matches!(name.as_ref(), "build" | ".gradle" | ".git" | ".idea") {
                    stack.push(path);
                }
                continue;
            }
            if !name.ends_with(".kt") && !name.ends_with(".java") {
                continue;
            }
            checked += 1;
            if checked > 5000 {
                return None; // enough scanning for a starter config
            }
            let Ok(content) = fs::read_to_string(&path) else {
                continue;
            };
            if content.contains("import org.koin") {
                return Some("Koin");
            }
            if content.contains("@HiltAndroidApp") || content.contains("@AndroidEntryPoint") {
                return Some("Hilt");
            }
            if content.contains("@Module") || content.contains("@Provides") {
                return Some("Dagger");
            }
        }
    }
    None
}
