#!/usr/bin/env bash
# Point the Homebrew tap at a released version.
#
# The formula pins four binaries by URL and sha256, and updating it by hand
# means it silently drifts: the tap sat on 0.10.2 while the crate shipped
# 0.13.0, so every `brew install` handed out a tool three releases behind,
# with false positives that had already been fixed.
#
# Checksums come from the .sha256 assets the release workflow already
# publishes, so nothing is recomputed and nothing can disagree with what was
# signed.
#
# Usage: scripts/update-homebrew-tap.sh <version>   # e.g. 0.13.0
#
# Needs gh authenticated with write access to the tap repo.

set -euo pipefail

VERSION="${1:?usage: update-homebrew-tap.sh <version>}"
VERSION="${VERSION#v}"
SOURCE_REPO="${SOURCE_REPO:-KevinDoremy/SearchDeadCode}"
TAP_REPO="${TAP_REPO:-KevinDoremy/homebrew-tap}"
FORMULA_PATH="Formula/searchdeadcode.rb"
TAG="v$VERSION"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The .sha256 files hold "<hash>  <filename>"; keep the hash.
checksum_for() {
  local asset="$1"
  gh release download "$TAG" --repo "$SOURCE_REPO" \
    --pattern "$asset.sha256" --dir "$work" --clobber >/dev/null
  awk '{print $1}' "$work/$asset.sha256"
}

echo "Reading checksums from $SOURCE_REPO $TAG"
MAC_X64="$(checksum_for searchdeadcode-macos-x86_64)"
MAC_ARM="$(checksum_for searchdeadcode-macos-aarch64)"
LNX_X64="$(checksum_for searchdeadcode-linux-x86_64)"
LNX_ARM="$(checksum_for searchdeadcode-linux-aarch64)"

for pair in "macos-x86_64:$MAC_X64" "macos-aarch64:$MAC_ARM" \
            "linux-x86_64:$LNX_X64" "linux-aarch64:$LNX_ARM"; do
  if [ -z "${pair#*:}" ]; then
    echo "error: no checksum for ${pair%%:*} in $TAG" >&2
    exit 1
  fi
done

base="https://github.com/$SOURCE_REPO/releases/download/$TAG"

cat > "$work/searchdeadcode.rb" <<FORMULA
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh. Edits here are overwritten on
# the next release.
class Searchdeadcode < Formula
  desc "Fast CLI tool to detect dead/unused code in Android projects (Kotlin & Java)"
  homepage "https://github.com/$SOURCE_REPO"
  version "$VERSION"
  license "MIT"

  on_macos do
    on_intel do
      url "$base/searchdeadcode-macos-x86_64"
      sha256 "$MAC_X64"
    end
    on_arm do
      url "$base/searchdeadcode-macos-aarch64"
      sha256 "$MAC_ARM"
    end
  end

  on_linux do
    on_intel do
      url "$base/searchdeadcode-linux-x86_64"
      sha256 "$LNX_X64"
    end
    on_arm do
      url "$base/searchdeadcode-linux-aarch64"
      sha256 "$LNX_ARM"
    end
  end

  def install
    # Homebrew downloads the single platform binary above under its asset
    # name; install it under the name users type.
    bin.install Dir["*"].first => "searchdeadcode"
  end

  test do
    assert_match "$VERSION", shell_output("#{bin}/searchdeadcode --version")
  end
end
FORMULA

current="$(gh api "repos/$TAP_REPO/contents/$FORMULA_PATH" --jq '.content' 2>/dev/null | base64 -d || true)"
if [ "$current" = "$(cat "$work/searchdeadcode.rb")" ]; then
  echo "Tap already describes $VERSION, nothing to push."
  exit 0
fi

sha="$(gh api "repos/$TAP_REPO/contents/$FORMULA_PATH" --jq '.sha' 2>/dev/null || true)"
args=(
  --method PUT
  "repos/$TAP_REPO/contents/$FORMULA_PATH"
  -f "message=searchdeadcode $VERSION"
  -f "content=$(base64 < "$work/searchdeadcode.rb" | tr -d '\n')"
)
[ -n "$sha" ] && args+=(-f "sha=$sha")

gh api "${args[@]}" >/dev/null
echo "Tap now points at $VERSION."
